version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: banking
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build: ./core-service
    depends_on:
      - db
    environment:
      DATASOURCE_URL: jdbc:postgresql://db:5432/banking
      DATASOURCE_USERNAME: myuser
      DATASOURCE_PASSWORD: mypassword
    ports:
      - "8080:8080"

volumes:
  postgres-data:
