version: '3.8'

services:
  currency-db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: currency
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5433:5432"
    volumes:
      - currency-data:/var/lib/postgresql/data

volumes:
  currency-data: